Allow to pick principle from context item
collective/sc.contentrules.localrole pull request #19
Opened 2018-11-12 23:12 UTC by rodfersou

closes #2

2018-11-13 03:54 UTC, djay requested changes
Looking much better. I've included some wording changes.

I'd also like to see the readme updated and include some screenshots so its easier to understand. then I think we are ready to go.

2018-11-13 03:54 UTC, djay commented on src/sc/contentrules/localrole/interfaces.py
> +                   description=_(u"Pick principle from context."),
I think we need some wording a bit more user friendly on both fields to explain the situation. We also need an invarient as they have to pick one or the other but not both. 
I suspect to make it easier to understand we get rid of the text in the principle field that uses interpolation as then we'd have to explain why it only works for some fields and not others.

So we have
User/Group ID: Enter the user or group id who should receive the permission in sharing (or pick a field below)

Field with User/Group ID: Pick a field which contains user/group ID to receive the permission. If the field is not found not permission will be set in sharing.


Note: we should change to use the word "permission" as thats what the sharing dialog uses. And in fact the wording on the rule should be about sharing since "localrole" is never used in the UI.

2018-11-13 10:04 UTC, rodfersou commented on src/sc/contentrules/localrole/interfaces.py
> +                   description=_(u"Pick principle from context."),
> We also need an invarient as they have to pick one or the other but not both.
Can you give me an example on how it is implemented?

2018-11-13 15:02 UTC, rodfersou commented on src/sc/contentrules/localrole/interfaces.py
> +                   description=_(u"Pick principle from context."),
Okay.. I think this is what you are talking about https://docs.plone.org/develop/addons/schema-driven-forms/customising-form-behaviour/validation.html#form-level-validation

2018-11-13 15:41 UTC, rodfersou commented
@djay Please take another look

2018-11-14 03:17 UTC, djay submitted a review, later dismissed
Looking good. Now just need the documentation changes. I might have a go today but would be good if you add screenshots

2018-11-20 11:05 UTC, instification approved these changes

2018-11-20 11:55 UTC, merged